// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Event struct {
	ID               int64
	Name             string
	Description      string
	Location         string
	Datatimecreating time.Time
	UserId           int32
	Datetimeupdating time.Time
}

type Register struct {
	ID      int64
	Userid  int32
	Eventid int32
}

type User struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
}
